// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zjbsrrauuteqvculavhl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InpqYnNycmF1dXRlcXZjdWxhdmhsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk5Nzc3OTAsImV4cCI6MjA2NTU1Mzc5MH0.XleXt-B4yPWxfBb3yidxKZMw7AcsAxmBvvC3kX5Kvig";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);